# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

namespace: gatekeeper-system

resources:
  - manifests/rbac.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  # Uncomment the following line to create an ingress if you want to expose the
  # the app to the outside. Remember to edit the file and set the host accordingly.
  # - manifests/ingress.yaml

# Uncomment the following patch to enable OIDC authentication.
# Remember to edit the file to set the right values.
# patchesStrategicMerge:
#   - manifests/enable-oidc.yaml

images:
  - name: quay.io/sighup/gatekeeper-policy-manager
    newTag: "v0.3.0"
